#!/bin/bash

get_domid_by_uuid(){
	xe vm-list is-a-template=false is-a-snapshot=false is-control-domain=false uuid=$1 power-state=running params=domid| grep uuid | awk -F: '{print $2}'
}

get_name_by_uuid(){
	xe vm-list is-a-template=false is-a-snapshot=false is-control-domain=false uuid=$1 power-state=running params=name-label| grep name-label | awk -F: '{print $2}'
}

list_of_current_vms(){
	for uuid in $(xe vm-list is-a-template=false is-a-snapshot=false is-control-domain=false power-state=running | grep uuid | awk '{print $5}'); do
		echo "${uuid}:$(get_name_by_uuid ${uuid})"
	done
}

set_vm_data(){
#Set VM's data to xenbus
	uuid=$1
	domid=$( get_domid_by_uuid ${uuid} )
	vm_data=$( get_name_by_uuid ${uuid} )
	for dat in $vm_data; do
		p_name=`echo $data | awk -F: '{print $1}'`
		p_value=`echo $data | awk -F: '{print $2}'`
		xenstore-write /local/domain/${domid}/customFields/${p_name} = ${vm_data}
	done
}

get_vm_data(){
#Get VM's data (additional fields) from VM's metadata
	xe vm-list uuid=$1 params=other-config | grep -oP 'XenCenter.CustomFields.eth\d:\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
}

while getopts "" option; do
	case $option in
		*)usage;;
	esac
done
